# config.yaml
data_path: "/var/log/TUF2000/"
log_file: "/var/log/TUF2000/tuf2000.log"

serial:
  port: "/dev/ttyUSB0"
  baudrate: 9600
  bytesize: 8
  parity: "N"
  stopbits: 1
  timeout: 1

base_keys:
  - {label: "Menu", reg: 59, val: 60}
  - {label: "Enter", reg: 59, val: 61}
  - {label: "Up", reg: 59, val: 62}
  - {label: "down", reg: 59, val: 63}
  - {label: "0", reg: 59, val: 48}
  - {label: "1", reg: 59, val: 49}
  - {label: "2", reg: 59, val: 50}
  - {label: "3", reg: 59, val: 51}
  - {label: "4", reg: 59, val: 52}
  - {label: "5", reg: 59, val: 53}
  - {label: "6", reg: 59, val: 54}
  - {label: "7", reg: 59, val: 55}
  - {label: "8", reg: 59, val: 56}
  - {label: "9", reg: 59, val: 57}
  - {label: ".", reg: 59, val: 58}

function_keys:
  - {label: "sh Pipe ext Diam", reg: 60, val: 17}
  - {label: "sh Pipe Thickness", reg: 60, val: 18}
  - {label: "sh Pipe material", reg: 60, val: 20}
  - {label: "sh spacing", reg: 60, val: 37}
  - {label: "sh Pipe material", reg: 60, val: 20}
  - {label: "sh fluid", reg: 60, val: 32}
  - {label: "sh transducer type", reg: 60, val: 35}
  - {label: "sh flow rate unit", reg: 60, val: 49}
  - {label: "sh flow rate", reg: 60, val: 00}
  - {label: "sh error code", reg: 60, val: 08}
  

composite_keys: []


action_keys:
  - {label: "flowGlobal", action: "record", addr: "0001", nbReg: 2, format: "REAL4", recurrence: "10",file: "flowGlobal.csv"}
  - {label: "resetGlobal", action: "deleteFile", file: "flowGlobal.csv"} 
  - {label: "flowRaspail", action: "record", addr: "0001", nbReg: 2, format: "REAL4", recurrence: "10",file: "flowRaspail.csv"}
  - {label: "resetRaspail", action: "deleteFile", file: "flowRaspail.csv"}
  - {label: "flowReneHamon", action: "record", addr: "0001", nbReg: 2, format: "REAL4", recurrence: "10", file: "flowReneHamon.csv"}
  - {label: "resetReneHamon", action: "deleteFile", file: "flowReneHamon.csv"}
  - {label: "flowLaTour", action: "record", addr: "0001", nbReg: 2, format: "REAL4", recurrence: "10",file: "flowLaTour.csv"}
  - {label: "resetLaTour", action: "deleteFile", file: "flowLaTour.csv"} 
  - {label: "flowVictorHugo", action: "record", addr: "0001", nbReg: 2, format: "REAL4", recurrence: "10",file: "flowVictorHugo.csv"}
  - {label: "resetVictorHugo", action: "deleteFile", file: "flowVictorHugo.csv"} 

