# config.yaml
data_path: "/var/log/TUF2000/"

serial:
  port: "/dev/ttyUSB0"
  baudrate: 9600
  bytesize: 8
  parity: "N"
  stopbits: 1
  timeout: 1

base_keys:
  - {label: "Menu", reg: 59, val: 60}
  - {label: "Enter", reg: 59, val: 61}
  - {label: "Up", reg: 59, val: 62}
  - {label: "down", reg: 59, val: 63}
  - {label: "0", reg: 59, val: 48}
  - {label: "1", reg: 59, val: 49}
  - {label: "2", reg: 59, val: 50}
  - {label: "3", reg: 59, val: 51}
  - {label: "4", reg: 59, val: 52}
  - {label: "5", reg: 59, val: 53}
  - {label: "6", reg: 59, val: 54}
  - {label: "7", reg: 59, val: 55}
  - {label: "8", reg: 59, val: 56}
  - {label: "9", reg: 59, val: 57}
  - {label: ".", reg: 59, val: 58}

function_keys:
  - {label: "Pipe ext Diam", reg: 60, val: 17}
  - {label: "Pipe Thickness", reg: 60, val: 18}
  - {label: "Pipe material", reg: 60, val: 20}

composite_keys:
  - label: "set pipe ext diameter"
    sequence: ["Menu", "1", "1", "Enter"]
  - label: "set pipe thickness"
    sequence: ["Menu", "1", "2", "Enter"]
  - label: "set pipe material"
    sequence: ["Menu", "1", "4", "Enter"]
  - label: "show spacing"
    sequence: ["Menu", "2", "5"]
    newline: true
  - label: "show error code"
    sequence: ["Menu", "0", "8"]

action_keys:
  - {label: "flowRaspail", action: "record", addr: "0001", nbReg: 2, format: "REAL4", recurrence: "10"}
  - {label: "velocity", action: "record", addr: "0005", nbReg: 2, format: "REAL4", recurrence: "5"}
  - {label: "resetRaspail", action: "deleteFile", file: "flowRaspail"}